name = "Quantic"
uuid = "1b94b867-1af3-47f4-8e09-7d16134b4c5f"
repo = "git@github.com:bsc-quantic/Registry.git"
description = "Registry of packages developed at BSC-Quantic group"

[packages]
b9105292-1415-45cf-bff1-d6ccf71e6143 = { name = "Quac", path = "Q/Quac" }
