name = "Quantic"
uuid = "1b94b867-1af3-47f4-8e09-7d16134b4c5f"
repo = "git@github.com:bsc-quantic/Registry.git"
description = "Registry of packages developed at BSC-Quantic group"

[packages]
21fe5c4b-a943-414d-bf3e-516f24900631 = { name = "Muscle", path = "M/Muscle" }
6bcc0789-44bc-4f47-9004-c8ca82614e89 = { name = "Lexers", path = "L/Lexers" }
85d41934-b9cd-44e1-8730-56d86f15f3ec = { name = "Tenet", path = "T/Tenet" }
8a0c07fa-ade5-4b2a-b81a-b192b2bedf88 = { name = "Extrae", path = "E/Extrae" }
a57d67a0-4683-47ff-be60-6114e830558b = { name = "Tensors", path = "T/Tensors" }
b1794770-133b-4de1-afb4-526377e9f4c5 = { name = "EinExprs", path = "E/EinExprs" }
b9105292-1415-45cf-bff1-d6ccf71e6143 = { name = "Quac", path = "Q/Quac" }
