name = "Quantic"
uuid = "1b94b867-1af3-47f4-8e09-7d16134b4c5f"
repo = "git@github.com:bsc-quantic/Registry.git"
description = "Registry of packages developed at BSC-Quantic group"

[packages]
0dfb065c-ad45-4a42-9a50-cb82c165eb0b = { name = "QuacIO", path = "Q/QuacIO" }
21fe5c4b-a943-414d-bf3e-516f24900631 = { name = "Muscle", path = "M/Muscle" }
2406e0f5-9e5e-4424-966e-8bc9c78b228f = { name = "QuantumTags", path = "Q/QuantumTags" }
2cc23cfe-e55e-4940-9d06-ab16fa76dba6 = { name = "TenetCore", path = "T/TenetCore" }
634dcf3f-6aa7-47ba-9e85-1fb329c9ebfe = { name = "Networks", path = "N/Networks" }
667c17eb-ab9b-4487-935f-1c621bb82497 = { name = "ImmutableArrays", path = "I/ImmutableArrays" }
6bcc0789-44bc-4f47-9004-c8ca82614e89 = { name = "Lexers", path = "L/Lexers" }
85d41934-b9cd-44e1-8730-56d86f15f3ec = { name = "Tenet", path = "T/Tenet" }
881a8f22-b5d0-48b0-96e5-a244b33f36d4 = { name = "Qrochet", path = "Q/Qrochet" }
8a0c07fa-ade5-4b2a-b81a-b192b2bedf88 = { name = "Extrae", path = "E/Extrae" }
a57d67a0-4683-47ff-be60-6114e830558b = { name = "Tensors", path = "T/Tensors" }
a795f257-962b-4b39-a4d8-031342f4c2f3 = { name = "Inherit", path = "I/Inherit" }
b1794770-133b-4de1-afb4-526377e9f4c5 = { name = "EinExprs", path = "E/EinExprs" }
b7eb675e-0b4b-4697-b10d-3f3487e0fa0a = { name = "Albacea", path = "A/Albacea" }
b9105292-1415-45cf-bff1-d6ccf71e6143 = { name = "Quac", path = "Q/Quac" }
d089a002-103b-496c-a4e3-58f90cf955b0 = { name = "BijectiveDicts", path = "B/BijectiveDicts" }
d2150e0e-da4c-4196-bcf0-8e0aeaf6db16 = { name = "Tangles", path = "T/Tangles" }
d83dbd90-3e00-4b33-84f1-398adcf3b35e = { name = "DelegatorTraits", path = "D/DelegatorTraits" }
