name = "Quantic"
uuid = "1b94b867-1af3-47f4-8e09-7d16134b4c5f"
repo = "git@github.com:bsc-quantic/Registry.git"
description = "Registry of packages developed at BSC-Quantic group"

[packages]
6bcc0789-44bc-4f47-9004-c8ca82614e89 = { name = "Lexers", path = "L/Lexers" }
85d41934-b9cd-44e1-8730-56d86f15f3ec = { name = "Tenet", path = "T/Tenet" }
8a0c07fa-ade5-4b2a-b81a-b192b2bedf88 = { name = "Extrae", path = "E/Extrae" }
b9105292-1415-45cf-bff1-d6ccf71e6143 = { name = "Quac", path = "Q/Quac" }
