on:
  create:
permissions:
  pull-requests: write
jobs:
  Registrator:
    if: ${{ startsWith(github.ref, 'refs/heads/registrator') }}
    runs-on: ubuntu-latest
    steps:
      - name: Open Pull Request
        run: gh pr create -B master -H ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}