name: Register package PR
on:
  create:
permissions:
  pull-requests: write
jobs:
  Registrator:
    if: ${{ startsWith(github.ref, 'refs/heads/registrator') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Open Pull Request
        run: |
          git checkout ${{ github.ref_name }}
          gh pr create --fill
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}