name: TagBot Triggers
on:
  pull_request:
    types:
      - closed
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  trigger:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # v3.3.0
      - run: chmod +x .ci/instantiate.sh
      - run: |
          using Pkg
          Pkg.Registry.add("General")
          Pkg.Registry.add(RegistrySpec(url = "https://github.com/bsc-quantic/Registry.git"))
        shell: julia --color=yes {0}
        env:
          JULIA_PKG_SERVER: ""
      - run: julia --color=yes -e 'import Pkg; Pkg.Registry.update()'
      - run: .ci/instantiate.sh
      - run: julia --project=.ci -e 'using Pkg; Pkg.instantiate(); Pkg.add("RegistryCI")'
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.NISUS_APP_ID }}
          private_key: ${{ secrets.NISUS_PRIVATE_KEY }}
      - run: julia --project=.ci -e 'using RegistryCI.TagBot; TagBot.main()'
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
